// Generated by CoffeeScript 1.9.1
(function() {
  var fileContent, fs, http, readFile, server, sourceFile;

  fs = require('fs');

  http = require('http');

  sourceFile = '1.txt';

  fileContent = 'empty';

  readFile = function() {
    return fs.readFile(sourceFile, 'utf-8', function(error, data) {
      if (error) {
        return console.log(error);
      } else {
        return fileContent = data;
      }
    });
  };

  fs.watchFile(sourceFile, readFile);

  server = http.createServer(function(request, response) {
    console.log(fileContent);
    return response.end(fileContent);
  });

  server.listen(8080, '127.0.0.1');

}).call(this);
